# -*- coding: utf-8 -*-
"""patient_map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1f7rH0o9h7y2Zbuuulhlpjt2m0cq9su
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install folium

import pandas as pd
from datetime import datetime

# CSV 파일 읽기
data = pd.read_excel('latitude_longitude.xlsx')
# 데이터 확인
print(data.head())
print(len(data))

import folium
import numpy as np
import math

# 2. 지도 초기화 (중심 좌표는 데이터의 평균 좌표)
center_location = [data['Latitude'].mean(), data['Longitude'].mean()]
map_object = folium.Map(location=center_location, zoom_start=13)

# 지하철 역정보
#
station_location = [
{'Latitude': 37.536857, 'Longitude': 127.085024}, # 구의
{'Latitude': 37.492426, 'Longitude': 126.895293}, # 대림
{'Latitude': 37.540408, 'Longitude': 127.069231}, # 건대입구
{'Latitude': 37.556748, 'Longitude': 126.923643}, # 홍대입구
{'Latitude': 37.555153, 'Longitude': 126.93689}, # 신촌
{'Latitude': 37.497958, 'Longitude': 127.027539}, # 강남
{'Latitude': 37.520731, 'Longitude': 127.103738}, # 잠실새내
{'Latitude': 37.533877, 'Longitude': 126.902011}, # 당산
{'Latitude': 37.550025, 'Longitude': 126.914557}, # 합정
{'Latitude': 37.520688, 'Longitude': 127.103836}, # 잠실나루
{'Latitude': 37.564504, 'Longitude': 127.028872}, # 상왕십리
{'Latitude': 37.525766, 'Longitude': 126.896627}, # 영등포구청
{'Latitude': 37.517993, 'Longitude': 126.894766}, # 문래
{'Latitude': 37.520218, 'Longitude': 126.852849}, # 신정네거리
{'Latitude': 37.561159, 'Longitude': 127.035505}, # 왕십리
{'Latitude': 37.493957, 'Longitude': 127.014631}, # 교대
{'Latitude': 37.565681, 'Longitude': 127.019488}, # 신당
{'Latitude': 37.504257, 'Longitude': 127.048174}, # 선릉
{'Latitude': 37.481469, 'Longitude': 126.997627}, # 방배
{'Latitude': 37.557407, 'Longitude': 126.956079}, # 아현
{'Latitude': 37.544628, 'Longitude': 127.055983}, # 성수
{'Latitude': 37.512194, 'Longitude': 126.865193}, # 양천구청
{'Latitude': 37.556734, 'Longitude': 126.945897}, # 이대
{'Latitude': 37.54718, 'Longitude': 127.047413}, # 뚝섬
{'Latitude': 37.511008, 'Longitude': 127.073641}, # 종합운동장
{'Latitude': 37.49191, 'Longitude': 127.007945}, # 서초
{'Latitude': 37.500658, 'Longitude': 127.03643}, # 역삼
{'Latitude': 37.508827, 'Longitude': 127.063203}, # 삼성
{'Latitude': 37.559742, 'Longitude': 126.964455}, # 충정로
{'Latitude': 37.565998, 'Longitude': 126.982569}, # 을지로입구
{'Latitude': 37.565609, 'Longitude': 127.009083}, # 동대문역사문화공원
{'Latitude': 37.566292, 'Longitude': 126.991773}, # 을지로3가
{'Latitude': 37.566412, 'Longitude': 126.977863}, # 용답
{'Latitude': 37.563534, 'Longitude': 126.975271}, # 시청
{'Latitude': 37.55658, 'Longitude': 127.043504}, # 한양대
{'Latitude': 37.566611, 'Longitude': 126.998122}, # 을지로 4가
{'Latitude': 37.56147, 'Longitude': 127.056348}, # 신답
{'Latitude': 37.574012, 'Longitude': 127.03811}, # 용두
{'Latitude': 37.574653, 'Longitude': 127.025158}, # 신설동
{'Latitude': 37.514759, 'Longitude': 126.882586},] # 도림천
{'Latitude': 37.513305, 'Longitude': 127.100129}, # 잠실
{'Latitude': 37.535161, 'Longitude': 127.094684}, # 강변
{'Latitude': 37.476536, 'Longitude': 126.981631}, # 사당

top_station_lacation = [
{'Latitude': 37.484216, 'Longitude': 126.929573}, # 신림
{'Latitude': 37.485005, 'Longitude': 126.902626}, # 구로디지털단지
{'Latitude': 37.481233, 'Longitude': 126.952745}, # 서울대입구
{'Latitude': 37.508815, 'Longitude': 126.891222}, # 신도림
{'Latitude': 37.487534, 'Longitude': 126.913279}, # 신대방
{'Latitude': 37.47693, 'Longitude': 126.963783}, # 낙성대
{'Latitude': 37.482416, 'Longitude': 126.941896}, # 봉천
]



# 새로지을곳 좌표 랜덤으로 지정
# 2km 반경
seed= 42
np.random.seed(seed)

# 90% -> 42개
# 75% -> 35
def generate_random_coordinates(center, radius_km, count=5):
    random_coords = []
    radius_deg = radius_km / 111  # Convert radius from km to degrees

    angles = np.random.uniform(0, 2 * math.pi, count)
    distances = np.random.uniform(0, radius_deg, count)

    delta_lat = distances * np.cos(angles)
    delta_lon = distances * np.sin(angles) / np.cos(np.radians(center['Latitude']))

    new_lats = center['Latitude'] + delta_lat
    new_lons = center['Longitude'] + delta_lon

    for lat, lon in zip(new_lats, new_lons):
        random_coords.append({'Latitude': lat, 'Longitude': lon})

    return random_coords

new_office_location = []
for i in range(7) :
    station = top_station_lacation[i]
    new_office_location.extend(generate_random_coordinates(station, 2))


# 지하철 역은 녹색으로 표시
for loc in station_location :
    folium.Marker(
        location=[loc['Latitude'], loc['Longitude']],
        icon=folium.Icon(color='green')  # 녹색 마커
    ).add_to(map_object)

# 승차많지만 주변에 공유오피스 없는 역은 빨간색으로
for loc in top_station_lacation :
    folium.Marker(
        location=[loc['Latitude'], loc['Longitude']],
        icon=folium.Icon(color='red')  # 빨간색 마커
    ).add_to(map_object)

# 새로 추가하는 오피스 위치는 역 주변으로
for loc in new_office_location :
    folium.Marker(
        location=[loc['Latitude'], loc['Longitude']],
        icon=folium.Icon(color='purple')  # 핑크 마커
    ).add_to(map_object)

# 3. 확진자 경로를 지도에 표시
for idx, row in data.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
    ).add_to(map_object)

# 4. 지도 표시
map_object
