# -*- coding: utf-8 -*-
"""Shared Office Scale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLFnL_ANB-6cwPNeB9cj4dgv1nyUPxkK
"""

import matplotlib.pyplot as plt

# when 75, 90
remote = [15, 25, 35, 45, 55]
#89000명 * 75%비율 * 재택근무 비율 * 재택근무 가능비율 * 평균 공유오피스 규모
x = [(89000*0.75*(i*0.01)*0.563)*10/4580.018 for i in remote]
y = [(89000*0.9*(i*0.01)*0.563)*10/4580.018 for i in remote]

plt.figure(figsize=(10, 6))
plt.plot(remote, x, marker='o', label='X Values: Worker ratio=75%')
plt.plot(remote, y, marker='s', label='Y Values: Worker ratio=90%')

# Setting specific x-ticks
plt.xticks(remote)

# Graph Details
plt.title('Remote Work place Scale by Remote Work Ratio', fontsize=14)
plt.xlabel('Remote Work Ratio', fontsize=12)
plt.ylabel('Remote Work place Scale', fontsize=12)
plt.legend()
plt.grid(True)

# Display the plot
plt.show()

fig, ax1 = plt.subplots(figsize=(12, 8))
num_trials = 1000

# 75%, 90%인 경우
ir_75 = [78.90360585, 76.56321092, 74.11374744, 72.66377158, 72.00116013]
ir_90 = [77.8842118, 74.99884289, 73.08418985, 71.23686197, 70.69809562]

# 평균 계산
average_ir_75 = [(value * 0.05 / num_trials) * 100 for value in ir_75]
average_ir_90 = [(value * 0.05 / num_trials) * 100 for value in ir_90]

# Remote Work Ratio 설정
remote = [15, 25, 35, 45, 55]  # 원래 x축 값
densities = [365 - int(365 * 0.75 * 0.01 * i) for i in remote]  # 밀도 계산

# 첫 번째 y축: 기존 데이터
ax1.bar(remote, average_ir_75, width=2, color='blue', alpha=0.3, label='Worker Ratio 75%')
ax1.bar(remote, average_ir_90, width=2, color='orange', alpha=1, label='Worker Ratio 90%')
ax1.set_xlabel("Remote Work Ratio (%)", fontsize=12)
ax1.set_ylabel('Average Probability of Infect(%)', fontsize=12, color='black')
ax1.tick_params(axis='y', labelcolor='black')
ax1.legend(loc='upper left', fontsize=10)

# 왼쪽 y축 범위 설정
ax1.set_ylim(0.34, max(max(average_ir_75), max(average_ir_90)) + 0.01)

# 막대 그래프 값 잇는 선 추가
ax1.plot(remote, average_ir_75, color='blue', marker='o', linewidth=2, label='Line for 75%')
ax1.plot(remote, average_ir_90, color='orange', marker='o', linewidth=2, label='Line for 90%')

# x축 설정
ax1.set_xticks(remote)
ax1.set_xticklabels(remote)

# 두 번째 y축: 새로운 데이터
x = [(89000 * 0.75 * (i * 0.01) * 0.563) * 10 / 4580.018 for i in remote]
y = [(89000 * 0.9 * (i * 0.01) * 0.563) * 10 / 4580.018 for i in remote]

ax2 = ax1.twinx()
ax2.plot(remote, x, marker='o', color='darkblue', linestyle='--', label='Worker Ratio 75%', linewidth=2)
ax2.plot(remote, y, marker='s', color='darkorange', linestyle='--', label='Worker Ratio 90%', linewidth=2)
ax2.set_ylabel('Remote Work Place Scale', fontsize=12, color='black')
ax2.tick_params(axis='y', labelcolor='black')
ax2.legend(loc='upper right', fontsize=10)

# 제목 및 레이아웃 설정
plt.title('Comparison of Infect Probability and Remote Work Scale', fontsize=14)
plt.grid(True)
plt.tight_layout()

# 그래프 표시
plt.show()

fig, ax1 = plt.subplots(figsize=(12, 8))
num_trials = 1000

# 75%, 90%인 경우
ir_75 = [236.23048911, 228.37708655, 221.09239864, 217.76895575, 215.26252706]
ir_90 = [234.5888799 , 227.15257544, 219.87494274, 214.30184312, 210.37477159]

# 평균 계산
average_ir_75 = [(value * 0.05 / num_trials) * 100 for value in ir_75]
average_ir_90 = [(value * 0.05 / num_trials) * 100 for value in ir_90]

# Remote Work Ratio 설정
remote = [15, 25, 35, 45, 55]  # 원래 x축 값
densities = [365 - int(365 * 0.75 * 0.01 * i) for i in remote]  # 밀도 계산

# 첫 번째 y축: 기존 데이터
ax1.bar(remote, average_ir_75, width=2, color='green', alpha=0.3, label='Worker Ratio 75%')
ax1.bar(remote, average_ir_90, width=2, color='red', alpha=1, label='Worker Ratio 90%')
ax1.set_xlabel("Remote Work Ratio(%)", fontsize=12)
ax1.set_ylabel('Average Probability of Infect(%)', fontsize=12, color='black')
ax1.tick_params(axis='y', labelcolor='black')
ax1.legend(loc='upper left', fontsize=10)

# 왼쪽 y축 범위 설정
ax1.set_ylim(1.0, max(max(average_ir_75), max(average_ir_90)) + 0.02)

# 막대 그래프 값 잇는 선 추가
ax1.plot(remote, average_ir_75, color='green', marker='o', linewidth=2, label='Line for 75%')
ax1.plot(remote, average_ir_90, color='red', marker='o', linewidth=2, label='Line for 90%')

# x축 설정
ax1.set_xticks(remote)
ax1.set_xticklabels(remote)

# 두 번째 y축: 새로운 데이터
x = [(89000 * 0.75 * (i * 0.01) * 0.563) * 10 / 4580.018 for i in remote]
y = [(89000 * 0.9 * (i * 0.01) * 0.563) * 10 / 4580.018 for i in remote]

ax2 = ax1.twinx()
ax2.plot(remote, x, marker='o', color='darkgreen', linestyle='--', label='Worker Ratio 75%', linewidth=2)
ax2.plot(remote, y, marker='s', color='darkred', linestyle='--', label='Worker Ratio 90%', linewidth=2)
ax2.set_ylabel('Remote Work Place Scale', fontsize=12, color='black')
ax2.tick_params(axis='y', labelcolor='black')
ax2.legend(loc='upper right', fontsize=10)

# 제목 및 레이아웃 설정
plt.title('Comparison of Infect Probability and Remote Work Scale', fontsize=14)
plt.grid(True)
plt.tight_layout()

# 그래프 표시
plt.show()

